name = "portfolio-cache-warmer"
main = "scripts/cache-warmer.js"
compatibility_date = "2024-01-01"
account_id = "df4c081395b0586e3f05b0aca5b6026f"

[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

[vars]
TARGET_URL = "https://ryanbumstead.com/"
