name = "portfolio-cache-warmer"
main = "../scripts/cache-warmer.js"
compatibility_date = "2024-01-01"
account_id = "a5ce6c8f5c4c7ffcb45465a402799984"

[triggers]
crons = ["*/5 * * * *"] # Run every 5 minutes

[vars]
TARGET_URL = "https://ryanbumstead.com/"
